name: Run code checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build packages
      run: cargo build --verbose
      
    - name: Run clippy
      run: cargo clippy 
      
    - name: Run tests
      run: cargo test

  format:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Run formatter
      run: cargo fmt
    
    - name: Print branch name
      run: echo "${{ github.head_ref }}"

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        message: "formatting changes"
        new_branch: "pupupu"
        push: false

